#!/usr/bin/env dash
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
pkill wofi
entries=" File\n Deadbeef\n Telegram\n Browser\n Editor\n Shotcut\n Audacity\n Calculator\n Gucharmap\n Gtk-Theme\n Blueman\n Wallpapers\n Terminal\n SmartTerminal"

selected=$(echo $entries|wofi -x 0 --width 100 --height 270 --dmenu --cache-file /dev/null --prompt=Applications | awk '{print tolower($2)}')

case $selected in
  file)
    pcmanfm;;
  deadbeef)
    deadbeef;;
  telegram)
    telegram-desktop;;
  browser)
    firefox;;
  editor)
    mousepad;;
  shotcut)
    shotcut;;
  audacity)
    audacity;;
  calculator)
    galculator;;
  gucharmap)
    gucharmap;;
  gtk-theme)
    dconf-editor;;
  blueman)
    blueman-manager;;
  wallpapers)
    waypaper;;
  terminal)
    foot;;
  smartterminal)
    foot -a SmartTerm;;
esac
